version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9095:9095" # Correspond au port défini dans server.port
    environment:
      SPRING_APPLICATION_NAME: gestionstock
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/gestionstock?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # Mot de passe vide, comme dans application.properties
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_THYMELEAF_PREFIX: classpath:/templates/
      SPRING_THYMELEAF_SUFFIX: .html
      SPRING_THYMELEAF_MODE: HTML
      SPRING_THYMELEAF_CACHE: "false"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET_VIEW: DEBUG
      LOGGING_LEVEL_ORG_THYMELEAF: DEBUG
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306" # Remap le port MySQL pour correspondre à localhost:3307
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: gestionstock
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "" # Mot de passe vide

volumes:
  mysql_data:
